### ISSUE TITLE
__main__.InvalidProperty: Property metrics.enabled is expected to be of type <type 'bool'>, but has value: true

### ISSUE THREAD

**Issue by wgrzelak** [GoogleCloudPlatform/marketplace-k8s-app-tools#386]
In the deployer after version `0.7.9`, the issue below exists:

```
Deploying application "apptest-g5xetpwh" in test mode
+ echo 'Deploying application "apptest-g5xetpwh" in test mode'
++ kubectl get applications.app.k8s.io/apptest-g5xetpwh --namespace=apptest-g5xetpwh '--output=jsonpath={.metadata.uid}'
+ app_uid=cf31f707-a711-11e9-9e81-42010a800077
++ kubectl get applications.app.k8s.io/apptest-g5xetpwh --namespace=apptest-g5xetpwh '--output=jsonpath={.apiVersion}'
+ app_api_version=app.k8s.io/v1beta1
+ /bin/expand_config.py --values_mode raw --app_uid cf31f707-a711-11e9-9e81-42010a800077
Traceback (most recent call last):
File "/bin/expand_config.py", line 268, in <module>
main()
File "/bin/expand_config.py", line 63, in main
values = expand(values, schema, app_uid=args.app_uid)
File "/bin/expand_config.py", line 138, in expand
validate_value_types(result, schema)
File "/bin/expand_config.py", line 164, in validate_value_types
k, prop.type, v))
__main__.InvalidProperty: Property metrics.enabled is expected to be of type <type 'bool'>, but has value: true
+ handle_failure
+ code=1
+ [[ -z apptest-g5xetpwh ]]
+ [[ -z apptest-g5xetpwh ]]
+ patch_assembly_phase.sh --status=Failed
+ for i in "$@"
+ case $i in
+ status=Failed
+ shift
+ [[ -z Failed ]]
+ [[ Failed =~ ^(Pending|Success|Failed)$ ]]
+ [[ -z apptest-g5xetpwh ]]
+ [[ -z apptest-g5xetpwh ]]
+ echo 'Marking deployment of application "apptest-g5xetpwh" as "Failed".'
Marking deployment of application "apptest-g5xetpwh" as "Failed".
```

It seems like the new deployer doesn't convert string to the boolean value anymore. For example: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/wordpress/Makefile#L44-L46

Is this the intended behavior?

**Comment by huyhg** [comment]
This is actually intended behavior in schema v2.

**Comment by wgrzelak** [comment]
@khajduczenia @ovk6 FYI
