### ISSUE TITLE
Cannot use custom image properties in schema v2

### ISSUE THREAD

**Issue by ovk6** [GoogleCloudPlatform/marketplace-k8s-app-tools#389]
Deployer fails when trying to overwrite image properties with custom values.
Looks like when expanding it checks upper level properties first, throws an exception, and only after that it would have tried to parse images properties.
https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/marketplace/deployer_util/expand_config.py#L74-L89

Example schema.yaml file:

```yaml
x-google-marketplace:
  schemaVersion: v2
...
  images:   
    '':         
      properties:        
        mariadb.image:
          type: FULL
...
```

Makefile:
```Makefile
...
ifdef IMAGE_MARIADB                                                       
  IMAGE_MARIADB_FIELD = , "mariadb.image": "$(IMAGE_MARIADB)"       
endif                                                               

APP_PARAMETERS ?= { \                                                
  "name": "$(NAME)", \                               
  "namespace": "$(NAMESPACE)" \             
  $(IMAGE_MARIADB_FIELD) \                    
}  
...
```

Error message:
```
Deploying application "mariadb-galera-1"
++ kubectl get applications.app.k8s.io/mariadb-galera-1 --namespace=default '--output=jsonpath={.metadata.uid}'
+ app_uid=a0db0f07-b205-11e9-8849-42010a8001e1
++ kubectl get applications.app.k8s.io/mariadb-galera-1 --namespace=default '--output=jsonpath={.apiVersion}'                                                                                                      + app_api_version=app.k8s.io/v1beta1                                                                                                                                                                              
+ /bin/expand_config.py --values_mode raw --app_uid a0db0f07-b205-11e9-8849-42010a8001e1
Traceback (most recent call last):                  
  File "/bin/expand_config.py", line 268, in <module>
    main()                         
  File "/bin/expand_config.py", line 63, in main
    values = expand(values, schema, app_uid=args.app_uid)
  File "/bin/expand_config.py", line 75, in expand                                              
    raise InvalidProperty('No such property defined in schema: {}'.format(k))
__main__.InvalidProperty: No such property defined in schema: mariadb.image
+ handle_failure
+ code=1                          
+ [[ -z mariadb-galera-1 ]]
+ [[ -z default ]]   
+ patch_assembly_phase.sh --status=Failed
```

**Comment by huyhg** [comment]
Yes, this is expected.

We can allow overriding individual image properties. However, I would like to understand the reason for this manual override in our Makefile. Can you elaborate on the use case here as well as the other options?

**Comment by wgrzelak** [comment]
I think we need during development/debugging. Sometimes we need to deploy the app in the develop environment with the image that is not defined in a Click to Deploy Makefile.
