### ISSUE TITLE
Latest deploy image fails to deploy app

### ISSUE THREAD

**Issue by depohmel** [GoogleCloudPlatform/marketplace-k8s-app-tools#478]
Here is the error from  deploy pod

```
INFO Application 'k10' owns 'Deployment/aggregatedapis-svc'
+ validate_app_resource.py --manifests /data/resources.yaml
INFO Reading /data/resources.yaml
Traceback (most recent call last):
  File "/bin/validate_app_resource.py", line 66, in validate_deploy_info_annotation
    parsed = json.loads(content)
  File "/opt/python3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/validate_app_resource.py", line 86, in <module>
    main()
  File "/bin/validate_app_resource.py", line 49, in main
    validate_deploy_info_annotation(mp_deploy_info, schema)
  File "/bin/validate_app_resource.py", line 81, in validate_deploy_info_annotation
    'marketplace.cloud.google.com/deploy-info annotation on the '
Exception: marketplace.cloud.google.com/deploy-info annotation on the Application resource must be valid JSON
+ handle_failure
+ code=1
```
The version which is failing:
```
Downloaded newer image for gcr.io/cloud-marketplace-tools/k8s/deployer_helm:latest
 ---> 7f4f4d072584
```

The version which worked fine 
```
Downloaded newer image for gcr.io/cloud-marketplace-tools/k8s/deployer_helm:latest
 ---> 79ff14136739
```

**Comment by huyhg** [comment]
Hello,

The particular error was: `Exception: marketplace.cloud.google.com/deploy-info annotation on the Application resource must be valid JSON`

The latest version of the deployer starts enforcing correctness of these required annotations. I've extracted your `Application`. It currently has the following annotation:

```yaml
metadata:
  annotations:
    marketplace.cloud.google.com/deploy-info: '{partner_id: "kasten-public", product_id: "K10", partner_name: "Kasten"}'
```

Its value should be corrected to a correct JSON string:

```json
{"partner_id": "kasten-public", "product_id": "kasten-k10", "partner_name": "Kasten"}
```

Note that I also corrected the `product_id` to `kasten-k10` because that is the correct ID, which can be found in the Partner Portal.

**Comment by depohmel** [comment]
Thanks for clarifying, is it possible to get notifications a few weeks before next time marketplace tools start endorsing anything?

**Comment by huyhg** [comment]
Sorry about the inconvenience! A few options:
- You can track our [releases](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/releases) for changes.
- Instead of `latest`, a specific version can be pinned to if it helps with your development velocity. We strongly recommend using `latest`, to get latest improvements and bug fixes. We generally try to be backward compatible. This particular case also falls into that category; it just happened that the annotation in the application had unexpected value (which would cause trouble downstream and thus it is worthwhile to fix).

**Comment by depohmel** [comment]
I'm not sure any of these options will help us to prevent future issues like this one. 
I would like to find and make changes before, things will be failing.  Is there a way of getting notifications prior to breaking changes will be released?

**Comment by depohmel** [comment]
@huyhg I made a change for application structure. and getting a new error:
```+ validate_app_resource.py --manifests /data/resources.yaml
INFO Reading /data/resources.yaml
Traceback (most recent call last):
  File "/bin/validate_app_resource.py", line 86, in <module>
    main()
  File "/bin/validate_app_resource.py", line 49, in main
    validate_deploy_info_annotation(mp_deploy_info, schema)
  File "/bin/validate_app_resource.py", line 66, in validate_deploy_info_annotation
    parsed = json.loads(content)
  File "/opt/python3.6/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
+ handle_failure
+ code=1
+ [[ -z k10 ]]
+ [[ -z g-launcher-zrgtxsluznzmt6op ]]
+ patch_assembly_phase.sh --status=Failed
+ for i in '"$@"'
Marking deployment of application "k10" as "Failed".
+ case $i in
+ status=Failed
+ shift
+ [[ -z Failed ]]
+ [[ Failed =~ ^(Pending|Success|Failed)$ ]]
+ [[ -z k10 ]]
+ [[ -z g-launcher-zrgtxsluznzmt6op ]]
+ echo 'Marking deployment of application "k10" as "Failed".'
+ [[ Failed == \S\u\c\c\e\s\s ]]
+ kubectl patch applications.app.k8s.io/k10 --output=json --namespace=g-launcher-zrgtxsluznzmt6op --type=merge --patch '{"spec": {"assemblyPhase": "Failed"}}'
Using /opt/kubectl/1.13/kubectl (server=1.13)
{
    "apiVersion": "app.k8s.io/v1beta1",
    "kind": "Application",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"app.k8s.io/v1beta1\",\"kind\":\"Application\",\"metadata\":{\"annotations\":{},\"name\":\"k10\",\"namespace\":\"g-launcher-zrgtxsluznzmt6op\"},\"spec\":{\"componentKinds\":[{\"kind\":\"ServiceAccount\"},{\"kind\":\"RoleBinding\"},{\"kind\":\"Job\"}],\"selector\":{\"matchLabels\":{\"app.kubernetes.io/name\":\"k10\"}}}}\n"
        },
        "creationTimestamp": "2020-02-07T00:29:20Z",
        "generation": 2,
        "name": "k10",
        "namespace": "g-launcher-zrgtxsluznzmt6op",
        "resourceVersion": "844518",
        "selfLink": "/apis/app.k8s.io/v1beta1/namespaces/g-launcher-zrgtxsluznzmt6op/applications/k10",
        "uid": "e19fb7ce-4940-11ea-8542-42010a8a001a"
    },
    "spec": {
        "assemblyPhase": "Failed",
        "componentKinds": [
            {
                "kind": "ServiceAccount"
            },
            {
                "kind": "RoleBinding"
            },
            {
                "kind": "Job"
            }
        ],
        "selector": {
            "matchLabels": {
                "app.kubernetes.io/name": "k10"
            }
        }
    }
}
+ exit 1
```

**Comment by bfeshti** [comment]
@depohmel did you find a way to resolve this? I am having the same issue.

**Comment by bfeshti** [comment]
@depohmel you should add single quotes around the JSON and it will work.
```marketplace.cloud.google.com/deploy-info: '{"partner_id": "kasten-public", "product_id": "kasten-k10", "partner_name": "Kasten"}'```
