### ISSUE TITLE
Error is thrown if test values.yaml is empty in helm based deployers

### ISSUE THREAD

**Issue by vcanaa** [GoogleCloudPlatform/marketplace-k8s-app-tools#479]
If test values.yaml is empty, the yaml parser returns None when the deployer tries to overlay it on top of the real values.yaml

Traceback (most recent call last):
  File "/bin/overlay_test_files.py", line 45, in <module>
    overlay_yaml_file(orig, dest)
  File "/bin/yaml_util.py", line 47, in overlay_yaml_file
    add_or_replace(y1, y2)
  File "/bin/yaml_util.py", line 30, in add_or_replace
    for key in orig:
TypeError: 'NoneType' object is not iterable

**Comment by devillexio** [comment]
I ended up defining a value that is not used anywhere or defined in any of the subcharts:

Chart values.yaml:
```yaml
placeholder: {}
```

Annoying but effective. 🙂
