### ISSUE TITLE
Schema validation warning

### ISSUE THREAD

**Issue by rstefan1** [GoogleCloudPlatform/marketplace-k8s-app-tools#525]
Schema validation does not work as expected.

I get the following error:

```
=== SCHEMA VALIDATION WARNING ===
WARNING: Schema is incompatible with the latest deployer, would fail with:

Traceback (most recent call last):
  File "/bin/validate_schema.py", line 35, in <module>
    main()
  File "/bin/validate_schema.py", line 31, in main
    schema_values_common.load_schema_and_validate(args)
  File "/bin/schema_values_common.py", line 65, in load_schema_and_validate
    return load_schema(parsed_args.schema_file).validate()
  File "/bin/schema_values_common.py", line 53, in memoized_func
    cache[key] = func(*args, **kwargs)
  File "/bin/schema_values_common.py", line 61, in load_schema
    return config_helper.Schema.load_yaml_file(parsed_args.schema_file)
AttributeError: 'str' object has no attribute 'schema_file'
==================================

```

**Comment by cbandy** [comment]
Fixed in #528.
