### ISSUE TITLE
exception: Set of resources includes multiple Applications even though there is only 1 application

### ISSUE THREAD

**Issue by samos123** [GoogleCloudPlatform/marketplace-k8s-app-tools#605]
I'm getting the below exception in the deployer even though there is only 1 application:
```
INFO Reading /data/manifest-expanded/chart.yaml            
Traceback (most recent call last):                         
  File "/bin/set_ownership.py", line 213, in <module>
    main()                                                 
  File "/bin/set_ownership.py", line 122, in main
    app = find_application_resource(resources)                                                                         
  File "/usr/bin/resources.py", line 69, in find_application_resource                                                  
    raise Exception("Set of resources includes multiple Applications")                                                 

```

**Comment by samos123** [comment]
damn in my case I had to change this:
```
FROM gcr.io/cloud-marketplace-tools/k8s/deployer_helm/onbuild:latest
```
to
```
FROM gcr.io/cloud-marketplace-tools/k8s/deployer_helm:latest
```
